baseurl = "https://www.finalatomicbuster.net"
title = "Vincent Martin"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Vincent Martin"
  info = "Software Engineer"
  description = "Vincent Martin's Personal Website"
  keywords = "blog,developer,personal"
  avatarurl = "images/me2.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  # since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]
  
  customCSS = []
  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/vincepmartin/"
[[params.social]]
  name = "Strava"
  icon = "fa fa-bicycle fa-2x"
  weight = 2
  url = "https://www.strava.com/athletes/robotburrito"

# Menu links
#[[menu.main]]
#  name = "Blog"
#  weight = 1
#  url  = "posts/"
[[menu.main]]
  name = "Side Projects"
  weight = 2
  url  = "sideprojects/sideprojects/"
[[menu.main]]
  name = "Resume"
  weight = 1
  url  = "resume/resume-latest/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/about-me/"
